name: Tests and Coverage
on:
  push:
    branches:
      - main
jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Build backend
        run: mvn package
        working-directory: ./back
        
      - name: Run backend tests
        run: mvn test
        working-directory: ./back
        
  frontend:  
    name: Frontend Build and Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front
    strategy:
      matrix:
        node-version: [20.x]
    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Install Angular CLI
        run: npm install -g @angular/cli
        
      - name: Install frontend dependencies
        run: npm install
        
      - name: Build frontend
        run: ng build 
        
      - name: Run frontend test
        run: npm run test:prod
        working-directory: ./front
        
      - name: Upload coverage report as a workflow artifact
        uses: actions/upload-artifact@v3
        with:
          name: karma-report
          path: front/coverage