name: Tests and Coverage
on:
  push:
    branches:
      - main
jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 17
      - name: Build backend
        run: mvn package
        working-directory: ./back
        
      - name: Run backend tests
        run: mvn test
        working-directory: ./back